# A different dataset than data_base.yaml, used for continued pretraining of the base model.
sources:
  - name: StoriesFTW
    type: hf
    hf_name: Sabijn/StoriesfortheWin
    split: train
    text_column: story

split:
  dev_fraction: 0.05
  test_fraction: 0.05
  seed: 42

paths:
  output_dir: /scratch-shared/sperdijk/storylm_p1_training/data/continue_StoriesFTW
