model:
  path: /scratch-shared/sperdijk/storylm_p1_training/models/continued_StoriesFTW_gpt2_60m_16k_basepoch1/final
  tokenizer_path: /scratch-shared/sperdijk/storylm_p1_training/models/continued_StoriesFTW_gpt2_60m_16k_basepoch1/final

data:
  config: data_continued.yaml   # resolved relative to this file's directory
  split: test                    # dev | test

eval_batch_size: 16

paths:
  output_dir: /scratch-shared/sperdijk/storylm_p1_training/results/continued_StoriesFTW_gpt2_60m_16k_basepoch1

wandb:
  entity: sabijn-leiden-university
  project: storytimelm-pretraining
  run_name: eval_continued_StoriesFTW_gpt2_60m_16k_basepoch1
  tags: [eval, continued, StoriesFTW, gpt2, 60m, 16k, basepoch1]

blimp:
  normalize_by_length: true
